### ISSUE TITLE
Не работают темы на Huawei Honor

### ISSUE THREAD

**Issue by stellio-team** [stellio-team/player#4]
Девайс - Huawei Honor 4c на андроид 6.0.1 Marshmallow.
Не работаю все темы.
Видео с проблемой - https://www.youtube.com/watch?v=lQSn114Y3qM&feature=youtu.be

**Comment by Emeraldbay3** [comment]
+1

**Comment by StellioTech** [comment]
+1

**Comment by stellio-team** [comment]
Исправлено
