### ISSUE TITLE
Баг с кнопкой назад

### ISSUE THREAD

**Issue by SlappyMan** [stellio-team/player#44]
При нажатии в область (1) и сразу после того как появляется окно с обложкой на весь экран,нажать область (2) "кнопку назад " при повторении этой комбинации от 3 до 10 рас вылетает на рабочий стол (сворачивается плеер)
![m2dvoqlwdb4](https://cloud.githubusercontent.com/assets/22604036/19056348/55b11d84-89d1-11e6-9f89-86c65fa73e57.jpg)

**Comment by stellio-team** [comment]
Исправлено в версии 4.930
