### ISSUE TITLE
Некачественное изображение обложки на экране блокировки.

### ISSUE THREAD

**Issue by StellioTech** [stellio-team/player#66]
При заблокированном экране меняется разрешение/качество обложки.
Скрины приложены.
Замечено на:
LG G4s,
Андроид 6.0 Marshmallow

![1](https://cloud.githubusercontent.com/assets/22610365/19678318/8d685a58-9a9d-11e6-9e4b-9dadaba4ec0d.jpg)
![2](https://cloud.githubusercontent.com/assets/22610365/19678319/8d697f96-9a9d-11e6-97ee-fc39d2410313.jpg)
![3](https://cloud.githubusercontent.com/assets/22610365/19678322/8d6d0c56-9a9d-11e6-8fee-9fab0279a419.jpg)
![4](https://cloud.githubusercontent.com/assets/22610365/19678323/8d7133da-9a9d-11e6-8efb-f9aad1b8cfb4.jpg)
![5](https://cloud.githubusercontent.com/assets/22610365/19678320/8d6a62b2-9a9d-11e6-9182-ba6b51b4e44c.jpg)
![6](https://cloud.githubusercontent.com/assets/22610365/19678321/8d6b2774-9a9d-11e6-8662-3beeec95392b.jpg)

**Comment by stellio-team** [comment]
Исправлено в версии 4.930
