### ISSUE TITLE
Не отображается меню, отображается черная полоса (Xiaomi redmi 3)

### ISSUE THREAD

**Issue by StellioTech** [stellio-team/player#68]
Xiaomi redmi 3 
Android 5.1.1
Miui 8.0.2.0 
Stellio 4.921

Баг при попытке вызвать меню с действиями относительно плейлиста(³ точки)
меню не отображается, а появляется лишь черная полоса, как на фото.

Замечен только с плейлистами из групп. Относительно моего плейлиста, все работает корректно.

![photo_2016-10-26_12-02-15](https://cloud.githubusercontent.com/assets/22610365/19722329/755aec08-9b76-11e6-9f7b-c3689b24dec8.jpg)

![photo_2016-10-26_12-18-12](https://cloud.githubusercontent.com/assets/22610365/19722327/7558f3bc-9b76-11e6-91c5-ae1dbd8a7141.jpg)

![photo_2016-10-26_12-18-33](https://cloud.githubusercontent.com/assets/22610365/19722328/755ab44a-9b76-11e6-86e1-c914641c7141.jpg)

**Comment by stellio-team** [comment]
Будет исправлено в >= 4.90
