### ISSUE TITLE
Визуальный баг с трекбаром при альбомной ориентации экрана

### ISSUE THREAD

**Issue by StellioTech** [stellio-team/player#74]
Замечено на LG nexus 5

![aauq74whfne](https://cloud.githubusercontent.com/assets/22610365/20002517/918665b2-a281-11e6-845b-f4bcd105adbb.jpg)

![iw4k89fmrxu](https://cloud.githubusercontent.com/assets/22610365/20002518/918757ba-a281-11e6-86c9-4a66d5adb7d7.jpg)

**Comment by stellio-team** [comment]
Будет исправлено в следующем релизе
