### ISSUE TITLE
не устанавливаются темы, вместо этого на рабочем столе появляется ярлык с именем res/layout/preference_category.xml

### ISSUE THREAD

**Issue by ENOTfanatik** [stellio-team/player#8]
Телефон Huawei 5x(kiw-l21) пришло официальное обновление до Android 6.0.1 номер прошивки kiw-l21c10b350. Теперь не устанавливаются темы, вместо этого на рабочем столе появляется ярлык с именем res/layout/preference_category.xml. Так же на данной версии прошивки плеер при одновременной работе с yandex navigator заикается. на версии прошивки kiw-l21c10b130 с android 5.1.1 такого нет.
Ссылка для скачивания файлов: http://files.mail.ru/63D9A2A30B7A40828E0C6A3E686710D1

**Comment by Emeraldbay3** [comment]
+1
Телефон Huawei gx8 l03 a Android Marshmallow 6.0.1, ну устанавливается тема "Stellio ExoBlur Theme", в место этого на рабочем столе появляются файлы "res/layout/preference_categ..."

**Comment by Emeraldbay3** [comment]
+1
Не устанавливается тема "Stellio ExoBlur Theme", а вместо этого появляются файлы на рабочем столе.

**Comment by stellio-team** [comment]
Возможно на ZTE Blade A5

**Comment by stellio-team** [comment]
Huawei honor 4c

Huawei honor 5x

Huawei G9

Huawei Mate 8

Huawei P8

Huawei P9

Huawei H60-J1

**Comment by stellio-team** [comment]
Исправлено
